/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSuppliersIndexRouteImport } from './routes/_auth/suppliers/index'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthProductionIndexRouteImport } from './routes/_auth/production/index'
import { Route as AuthPickingIndexRouteImport } from './routes/_auth/picking/index'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth/orders/index'
import { Route as AuthCustomersIndexRouteImport } from './routes/_auth/customers/index'
import { Route as AuthSuppliersNewRouteImport } from './routes/_auth/suppliers/new'
import { Route as AuthSuppliersSupplierIdRouteImport } from './routes/_auth/suppliers/$supplierId'
import { Route as AuthProductsNewRouteImport } from './routes/_auth/products/new'
import { Route as AuthProductsProductIdRouteImport } from './routes/_auth/products/$productId'
import { Route as AuthOrdersNewRouteImport } from './routes/_auth/orders/new'
import { Route as AuthOrdersOrderIdRouteImport } from './routes/_auth/orders/$orderId'
import { Route as AuthInventoryScanRouteImport } from './routes/_auth/inventory/scan'
import { Route as AuthInventoryPredictionsRouteImport } from './routes/_auth/inventory/predictions'
import { Route as AuthCalendarIndexRouteImport } from './routes/_auth/calendar/index'
import { Route as AuthCustomersNewRouteImport } from './routes/_auth/customers/new'
import { Route as AuthCustomersCustomerIdRouteImport } from './routes/_auth/customers/$customerId'
import { Route as AuthProductionRecipesIndexRouteImport } from './routes/_auth/production/recipes/index'
import { Route as AuthProductionMaterialsIndexRouteImport } from './routes/_auth/production/materials/index'
import { Route as AuthProductionBatchesIndexRouteImport } from './routes/_auth/production/batches/index'
import { Route as AuthProductionRecipesNewRouteImport } from './routes/_auth/production/recipes/new'
import { Route as AuthProductionBatchesNewRouteImport } from './routes/_auth/production/batches/new'
import { Route as AuthProductionBatchesBatchIdRouteImport } from './routes/_auth/production/batches/$batchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuppliersIndexRoute = AuthSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductionIndexRoute = AuthProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPickingIndexRoute = AuthPickingIndexRouteImport.update({
  id: '/picking/',
  path: '/picking/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersIndexRoute = AuthCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuppliersNewRoute = AuthSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuppliersSupplierIdRoute = AuthSuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsNewRoute = AuthProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsProductIdRoute = AuthProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersNewRoute = AuthOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersOrderIdRoute = AuthOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryScanRoute = AuthInventoryScanRouteImport.update({
  id: '/inventory/scan',
  path: '/inventory/scan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryPredictionsRoute = AuthInventoryPredictionsRouteImport.update({
  id: '/inventory/predictions',
  path: '/inventory/predictions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarIndexRoute = AuthCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersNewRoute = AuthCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersCustomerIdRoute = AuthCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductionRecipesIndexRoute =
  AuthProductionRecipesIndexRouteImport.update({
    id: '/production/recipes/',
    path: '/production/recipes/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProductionMaterialsIndexRoute =
  AuthProductionMaterialsIndexRouteImport.update({
    id: '/production/materials/',
    path: '/production/materials/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProductionBatchesIndexRoute =
  AuthProductionBatchesIndexRouteImport.update({
    id: '/production/batches/',
    path: '/production/batches/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProductionRecipesNewRoute =
  AuthProductionRecipesNewRouteImport.update({
    id: '/production/recipes/new',
    path: '/production/recipes/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProductionBatchesNewRoute =
  AuthProductionBatchesNewRouteImport.update({
    id: '/production/batches/new',
    path: '/production/batches/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProductionBatchesBatchIdRoute =
  AuthProductionBatchesBatchIdRouteImport.update({
    id: '/production/batches/$batchId',
    path: '/production/batches/$batchId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/customers/new': typeof AuthCustomersNewRoute
  '/inventory/scan': typeof AuthInventoryScanRoute
  '/inventory/predictions': typeof AuthInventoryPredictionsRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/orders/new': typeof AuthOrdersNewRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/products/new': typeof AuthProductsNewRoute
  '/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/suppliers/new': typeof AuthSuppliersNewRoute
  '/customers/': typeof AuthCustomersIndexRoute
  '/orders/': typeof AuthOrdersIndexRoute
  '/picking/': typeof AuthPickingIndexRoute
  '/production/': typeof AuthProductionIndexRoute
  '/products/': typeof AuthProductsIndexRoute
  '/suppliers/': typeof AuthSuppliersIndexRoute
  '/production/batches/$batchId': typeof AuthProductionBatchesBatchIdRoute
  '/production/batches/new': typeof AuthProductionBatchesNewRoute
  '/production/recipes/new': typeof AuthProductionRecipesNewRoute
  '/production/batches/': typeof AuthProductionBatchesIndexRoute
  '/production/materials/': typeof AuthProductionMaterialsIndexRoute
  '/production/recipes/': typeof AuthProductionRecipesIndexRoute
  '/calendar/': typeof AuthCalendarIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/customers/new': typeof AuthCustomersNewRoute
  '/inventory/scan': typeof AuthInventoryScanRoute
  '/inventory/predictions': typeof AuthInventoryPredictionsRoute
  '/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/orders/new': typeof AuthOrdersNewRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/products/new': typeof AuthProductsNewRoute
  '/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/suppliers/new': typeof AuthSuppliersNewRoute
  '/customers': typeof AuthCustomersIndexRoute
  '/orders': typeof AuthOrdersIndexRoute
  '/picking': typeof AuthPickingIndexRoute
  '/production': typeof AuthProductionIndexRoute
  '/products': typeof AuthProductsIndexRoute
  '/suppliers': typeof AuthSuppliersIndexRoute
  '/production/batches/$batchId': typeof AuthProductionBatchesBatchIdRoute
  '/production/batches/new': typeof AuthProductionBatchesNewRoute
  '/production/recipes/new': typeof AuthProductionRecipesNewRoute
  '/production/batches': typeof AuthProductionBatchesIndexRoute
  '/production/materials': typeof AuthProductionMaterialsIndexRoute
  '/production/recipes': typeof AuthProductionRecipesIndexRoute
  '/calendar': typeof AuthCalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/_auth/customers/new': typeof AuthCustomersNewRoute
  '/_auth/inventory/scan': typeof AuthInventoryScanRoute
  '/_auth/inventory/predictions': typeof AuthInventoryPredictionsRoute
  '/_auth/calendar/': typeof AuthCalendarIndexRoute
  '/_auth/orders/$orderId': typeof AuthOrdersOrderIdRoute
  '/_auth/orders/new': typeof AuthOrdersNewRoute
  '/_auth/products/$productId': typeof AuthProductsProductIdRoute
  '/_auth/products/new': typeof AuthProductsNewRoute
  '/_auth/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/_auth/suppliers/new': typeof AuthSuppliersNewRoute
  '/_auth/customers/': typeof AuthCustomersIndexRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
  '/_auth/picking/': typeof AuthPickingIndexRoute
  '/_auth/production/': typeof AuthProductionIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
  '/_auth/suppliers/': typeof AuthSuppliersIndexRoute
  '/_auth/production/batches/$batchId': typeof AuthProductionBatchesBatchIdRoute
  '/_auth/production/batches/new': typeof AuthProductionBatchesNewRoute
  '/_auth/production/recipes/new': typeof AuthProductionRecipesNewRoute
  '/_auth/production/batches/': typeof AuthProductionBatchesIndexRoute
  '/_auth/production/materials/': typeof AuthProductionMaterialsIndexRoute
  '/_auth/production/recipes/': typeof AuthProductionRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/login'
  | '/customers/$customerId'
  | '/customers/new'
  | '/inventory/scan'
  | '/inventory/predictions'
  | '/orders/$orderId'
  | '/orders/new'
  | '/products/$productId'
  | '/products/new'
  | '/suppliers/$supplierId'
  | '/suppliers/new'
  | '/customers/'
  | '/orders/'
  | '/picking/'
  | '/production/'
  | '/products/'
  | '/suppliers/'
  | '/production/batches/$batchId'
  | '/production/batches/new'
  | '/production/recipes/new'
  | '/production/batches/'
  | '/production/materials/'
  | '/production/recipes/'
  | '/calendar/'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/login'
  | '/'
  | '/customers/$customerId'
  | '/customers/new'
  | '/inventory/scan'
  | '/inventory/predictions'
  | '/orders/$orderId'
  | '/orders/new'
  | '/products/$productId'
  | '/products/new'
  | '/suppliers/$supplierId'
  | '/suppliers/new'
  | '/customers'
  | '/orders'
  | '/picking'
  | '/production'
  | '/products'
  | '/suppliers'
  | '/production/batches/$batchId'
  | '/production/batches/new'
  | '/production/recipes/new'
  | '/production/batches'
  | '/production/materials'
  | '/production/recipes'
  | '/calendar'
  id:
  | '__root__'
  | '/_auth'
  | '/login'
  | '/_auth/'
  | '/_auth/customers/$customerId'
  | '/_auth/customers/new'
  | '/_auth/inventory/scan'
  | '/_auth/inventory/predictions'
  | '/_auth/calendar/'
  | '/_auth/orders/$orderId'
  | '/_auth/orders/new'
  | '/_auth/products/$productId'
  | '/_auth/products/new'
  | '/_auth/suppliers/$supplierId'
  | '/_auth/suppliers/new'
  | '/_auth/customers/'
  | '/_auth/orders/'
  | '/_auth/picking/'
  | '/_auth/production/'
  | '/_auth/products/'
  | '/_auth/suppliers/'
  | '/_auth/production/batches/$batchId'
  | '/_auth/production/batches/new'
  | '/_auth/production/recipes/new'
  | '/_auth/production/batches/'
  | '/_auth/production/materials/'
  | '/_auth/production/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers/': {
      id: '/_auth/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthSuppliersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/': {
      id: '/_auth/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthProductionIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/picking/': {
      id: '/_auth/picking/'
      path: '/picking'
      fullPath: '/picking/'
      preLoaderRoute: typeof AuthPickingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/': {
      id: '/_auth/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthCustomersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers/new': {
      id: '/_auth/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthSuppliersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers/$supplierId': {
      id: '/_auth/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/new': {
      id: '/_auth/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthProductsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/$productId': {
      id: '/_auth/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthProductsProductIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/new': {
      id: '/_auth/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthOrdersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/$orderId': {
      id: '/_auth/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthOrdersOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/scan': {
      id: '/_auth/inventory/scan'
      path: '/inventory/scan'
      fullPath: '/inventory/scan'
      preLoaderRoute: typeof AuthInventoryScanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/predictions': {
      id: '/_auth/inventory/predictions'
      path: '/inventory/predictions'
      fullPath: '/inventory/predictions'
      preLoaderRoute: typeof AuthInventoryPredictionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar/': {
      id: '/_auth/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthCalendarIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/new': {
      id: '/_auth/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthCustomersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/$customerId': {
      id: '/_auth/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthCustomersCustomerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/recipes/': {
      id: '/_auth/production/recipes/'
      path: '/production/recipes'
      fullPath: '/production/recipes/'
      preLoaderRoute: typeof AuthProductionRecipesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/materials/': {
      id: '/_auth/production/materials/'
      path: '/production/materials'
      fullPath: '/production/materials/'
      preLoaderRoute: typeof AuthProductionMaterialsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/batches/': {
      id: '/_auth/production/batches/'
      path: '/production/batches'
      fullPath: '/production/batches/'
      preLoaderRoute: typeof AuthProductionBatchesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/recipes/new': {
      id: '/_auth/production/recipes/new'
      path: '/production/recipes/new'
      fullPath: '/production/recipes/new'
      preLoaderRoute: typeof AuthProductionRecipesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/batches/new': {
      id: '/_auth/production/batches/new'
      path: '/production/batches/new'
      fullPath: '/production/batches/new'
      preLoaderRoute: typeof AuthProductionBatchesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/production/batches/$batchId': {
      id: '/_auth/production/batches/$batchId'
      path: '/production/batches/$batchId'
      fullPath: '/production/batches/$batchId'
      preLoaderRoute: typeof AuthProductionBatchesBatchIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCustomersCustomerIdRoute: typeof AuthCustomersCustomerIdRoute
  AuthCustomersNewRoute: typeof AuthCustomersNewRoute
  AuthInventoryScanRoute: typeof AuthInventoryScanRoute
  AuthInventoryPredictionsRoute: typeof AuthInventoryPredictionsRoute
  AuthOrdersOrderIdRoute: typeof AuthOrdersOrderIdRoute
  AuthOrdersNewRoute: typeof AuthOrdersNewRoute
  AuthProductsProductIdRoute: typeof AuthProductsProductIdRoute
  AuthProductsNewRoute: typeof AuthProductsNewRoute
  AuthSuppliersSupplierIdRoute: typeof AuthSuppliersSupplierIdRoute
  AuthSuppliersNewRoute: typeof AuthSuppliersNewRoute
  AuthCustomersIndexRoute: typeof AuthCustomersIndexRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
  AuthPickingIndexRoute: typeof AuthPickingIndexRoute
  AuthProductionIndexRoute: typeof AuthProductionIndexRoute
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
  AuthSuppliersIndexRoute: typeof AuthSuppliersIndexRoute
  AuthProductionBatchesBatchIdRoute: typeof AuthProductionBatchesBatchIdRoute
  AuthProductionBatchesNewRoute: typeof AuthProductionBatchesNewRoute
  AuthProductionRecipesNewRoute: typeof AuthProductionRecipesNewRoute
  AuthProductionBatchesIndexRoute: typeof AuthProductionBatchesIndexRoute
  AuthProductionMaterialsIndexRoute: typeof AuthProductionMaterialsIndexRoute
  AuthProductionRecipesIndexRoute: typeof AuthProductionRecipesIndexRoute
  AuthCalendarIndexRoute: typeof AuthCalendarIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthCustomersCustomerIdRoute: AuthCustomersCustomerIdRoute,
  AuthCustomersNewRoute: AuthCustomersNewRoute,
  AuthInventoryScanRoute: AuthInventoryScanRoute,
  AuthInventoryPredictionsRoute: AuthInventoryPredictionsRoute,
  AuthOrdersOrderIdRoute: AuthOrdersOrderIdRoute,
  AuthOrdersNewRoute: AuthOrdersNewRoute,
  AuthProductsProductIdRoute: AuthProductsProductIdRoute,
  AuthProductsNewRoute: AuthProductsNewRoute,
  AuthSuppliersSupplierIdRoute: AuthSuppliersSupplierIdRoute,
  AuthSuppliersNewRoute: AuthSuppliersNewRoute,
  AuthCustomersIndexRoute: AuthCustomersIndexRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
  AuthPickingIndexRoute: AuthPickingIndexRoute,
  AuthProductionIndexRoute: AuthProductionIndexRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
  AuthSuppliersIndexRoute: AuthSuppliersIndexRoute,
  AuthProductionBatchesBatchIdRoute: AuthProductionBatchesBatchIdRoute,
  AuthProductionBatchesNewRoute: AuthProductionBatchesNewRoute,
  AuthProductionRecipesNewRoute: AuthProductionRecipesNewRoute,
  AuthProductionBatchesIndexRoute: AuthProductionBatchesIndexRoute,
  AuthProductionMaterialsIndexRoute: AuthProductionMaterialsIndexRoute,
  AuthProductionRecipesIndexRoute: AuthProductionRecipesIndexRoute,
  AuthCalendarIndexRoute: AuthCalendarIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
